# Generated by Django 4.2.17 on 2024-12-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='mac_address',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
