# Generated by Django 4.2.17 on 2024-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0003_alter_ipaddressmodel_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
