# Generated by Django 4.2.17 on 2024-12-15 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ips', '0004_alter_ipaddressmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
