# Generated by Django 4.2.17 on 2024-12-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0007_alter_ipaddressmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddressmodel',
            name='comment',
            field=models.TextField(blank=True, max_length=61, null=True),
        ),
    ]
